### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by redviper2100** [j0hnk1m/music-download-bot#1]
I can see that on https://www.shazam.com/myshazam the text can be scraped easily. Is there other reason why you used an image and ocr it to get the song names? 

Thanks! 

Great project btw! Cheers!

**Comment by j0hnk1m** [comment]
If you take a look at the page source, you can see that the songs info are being loaded in by javascript, not html (after the request). I could have used other ways to get the javascript text, but I also just wanted to try Google's OCR technology.
